# This is the configuration file for our simulation parameters

input_file = "./input.xyz"
g1_output_file = "./output.g1.txt"
g2_output_file = "./output.g2.txt"
g3_output_file = "./output.g3.txt"
com_output_file = "./output.com.txt"


# equilibration time
T_EQ = 10

# List of molecule IDs (optional)
mol_ids = [605, 606, 607]

# Optional atom IDs (can be omitted)
atom_ids = [1, 2]

# Optional types (can be omitted)
types = [1, 2]
